config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = %w(white black red grey)
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: {in: COLORS}
  validates :sex, inclusion: { in: ['M', 'F']}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index 
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def new
    @cat = Cat.new
    render :new
  end
  
  def create
    # byebug
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    # debugger
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
    
  end
  
  private
  
  def cat_params
    params.require(:cat).permit(:color, :description, :sex, :name, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<% 
  if type == :new
    action = cats_url
    button_txt = "Create Cat"
  else
    button_txt = "Edit Cat"
    action = cat_url(cat)
  end
 %>
 
 <form action="<%= action %>" method="post">
   <% if type == :edit  %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  
   
   <label for="name">Name:
     <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>"><br>
   </label>
   
   <label for="sex">Sex:
     <input type="radio" name="cat[sex]" value="M" '<% if @cat.sex = 'M' %>' checked '<% end %>' > Male
     <input type="radio" name="cat[sex]" value="F" '<% if @cat.sex = 'F' %>' checked '<% end %>'>Female<br>
   </label>
   
   <label for="color">Color:
     <select name="cat[color]">
       <% if type == :new %>
        <option value="red" disabled="true" selected="true">-- select a color --</option>
      <% end %>
       
       <option value="red" '<% if @cat.color == 'red' %>' selected '<% end %>' >Red</option>
       <option value="black" '<% if @cat.color == 'black' %>' selected '<% end %>' >Black</option>
       <option value="white" '<% if @cat.color == 'white' %>' selected '<% end %>' >White</option>
       <option value="grey" '<% if @cat.color == 'grey' %>' selected '<% end %>'>Grey</option>
     </select><br>
   </label>
   
   <label for="birth_date">Birth Date:
     <input type="date" name="cat[birth_date]" value='<%= @cat.birth_date %>'><br>
   </label>
   
   <label for="description">Description: 
     <textarea name="cat[description]">'<%= @cat.description %>'</textarea>
   </label><br>
   <input type="submit" name="" value= '<%= button_txt %>'>
   
 </form>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat, type: :edit %>

app/views/cats/index.html.erb
<h1>All the Cats</h1>
<ul>
  <!-- <li> -->
    <% @cats.each do |cat| %>
      <li>
        <ul>
          <li><%= cat.name %></li>
          <li><%= cat.birth_date %></li>
          <li><%= cat.color %></li>
          <li><%= cat.sex %></li>
          <li><%= cat.description %></li>
          <li><a href="<%= cat_url(cat) %>">show cat</a></li>
          <br>
        </ul>
      </li>
    <% end %>
  <!-- </li> -->
</ul>

app/views/cats/new.html.erb
<%= render "form", cat: @cat, type: :new %>

app/views/cats/show.html.erb
<p>Cats attributes</p>
<table>
  <tr>
    <th>name</th>
    <th>sex</th>
    <th>color</th>
    <th>birth date</th>
    <th>description</th>
  </tr>
  <tr>
    <th><%= @cat.name %></th>
    <th><%= @cat.sex %></th>
    <th><%= @cat.color %></th>
    <th><%= @cat.birth_date %></th>
    <th><%= @cat.description %></th>
  </tr>
</table>
<a href="<%= edit_cat_url(@cat) %>">edit cat</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NintyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>